Movie Ticket Booking Service: MovieBookingService Class Reference
MovieBookingService Class Reference
A class representing a movie booking service.
#include <movie_booking_service.hpp>
Public Member Functions
MovieBookingService ()=default
Constructor.
~MovieBookingService ()=default
Destructor for the MovieBookingService class.
void addMovie (const std::shared_ptr< Movie > &movie)
Add a movie to the list of available movies.
void addTheater (const std::shared_ptr< Theater > &theater)
Add a theater to the list of available theaters.
const std::vector< std::shared_ptr< Movie > > & getAllMovies () const
Get a list of all playing movies.
std::vector< std::shared_ptr< Theater > > getTheatersForMovie (int movieId) const
Get theaters showing a specific movie.
std::vector< int > getAvailableSeats (int theaterId, int movieId) const
Get available (free/unbooked) seats for a specific theater and movie.
bool bookSeats (int theaterId, int movieId, const std::vector< int > &seatIds)
Book seats for a specific theater and movie.
bool isValidMovie (int movieId) const
Check if a movie with a given ID exists.
bool isMovieShownInTheater (int theaterId, int movieId) const
Validate and check if a theater shows a given movie.
std::string getMovieName (int movieId) const
Get the name of a movie by its ID.
std::string getTheaterName (int theaterId) const
Get the name of a theater by its ID.
Private Member Functions
bool allocateMovieToTheaters (const std::shared_ptr< Movie > &movie)
Allocate a movie to one or more theaters.
bool isValidTheater (int theaterId) const
Check if a theater with a given ID exists.
Private Attributes
std::mutex mBookingMutex
Mutex for synchronization of booking operations.
std::vector< std::shared_ptr< Movie > > mMovies
std::vector< std::shared_ptr< Theater > > mTheaters
std::unordered_map< int, std::vector< int > > mMovieTheaterAllocations
A map to track movie allocations to theaters.
Detailed Description
A class representing a movie booking service.
The MovieBookingService class provides methods for managing movie bookings, theaters, and seat allocations.
Member Function Documentation
addMovie()
void MovieBookingService::addMovie (const std::shared_ptr< Movie > & movie)
Add a movie to the list of available movies.
Parameters
movie A shared pointer to the movie to be added.
{
    // Add the movie to the list of movies
    {
        std::lock_guard<std::mutex> lock(mBookingMutex);
        mMovies.push_back(movie);
    }
    allocateMovieToTheaters(movie);
}
References allocateMovieToTheaters(), mBookingMutex, and mMovies.
addTheater()
void MovieBookingService::addTheater (const std::shared_ptr< Theater > & theater)
Add a theater to the list of available theaters.
Parameters
theater A shared pointer to the theater to be added.
{
    if (!theater) {
        // Handle null pointer
        return;
    }
    {
        std::lock_guard<std::mutex> lock(mBookingMutex);
        // Add the theater to the list of theaters
        mTheaters.push_back(theater);
    }
    bool isMovieAllocated = false;
    // Check if there are unallocated movies
    for (auto& movie : mMovies) {
        if (!movie->isAllocated) {
            if (allocateMovieToTheaters(movie)) {
                isMovieAllocated = true;
            }
        }
    }
    // If all movies are already allocated, randomly pick one movie
    if (!isMovieAllocated && !mMovies.empty()) {
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<int> dist(0, mMovies.size() - 1);
        int randomIndex = dist(gen);
        // Allocate the randomly picked movie to the new theater
        isMovieAllocated = allocateMovieToTheaters(mMovies[randomIndex]);
    }
}
References allocateMovieToTheaters(), mBookingMutex, mMovies, and mTheaters.
allocateMovieToTheaters()
bool MovieBookingService::allocateMovieToTheaters (const std::shared_ptr< Movie > & movie) private
Allocate a movie to one or more theaters.
This method allocates the specified movie to one or more theaters.
Parameters
movie A shared pointer to the movie to allocate to theaters.
Returns
True if the allocated, false otherwise.
{
    std::lock_guard<std::mutex> lock(mBookingMutex);
    int movieId = movie->id;
    if (!isValidMovie(movieId)) {
        // Handle invalid movie ID
        return false;
    }
    // Try to allocate the movie to an unallocated theater
    for (auto& theater : mTheaters) {
        if (!theater->isAllocated()) {
            theater->allocateMovie();
            mMovieTheaterAllocations[movieId].push_back(theater->getId());
            movie->isAllocated = true;
            return true;
        }
    }
    return false;
}
References isValidMovie(), mBookingMutex, mMovieTheaterAllocations, and mTheaters.
Referenced by addMovie(), and addTheater().
bookSeats()
bool MovieBookingService::bookSeats (int theaterId, int movieId, const std::vector< int > & seatIds)
Book seats for a specific theater and movie.
Parameters
theaterId The ID of the theater.
movieId The ID of the movie.
seatIds A vector of seat IDs to be booked.
Returns
True if seats were booked successfully, false otherwise.
{
    // Check if the theater and movie IDs are valid
    if (!isValidTheater(theaterId) || !isValidMovie(movieId) || seatIds.empty()) {
        return false; // Invalid theater or movie
    }
    std::lock_guard<std::mutex> lock(mBookingMutex);
    // Get the theater associated with the provided theaterId
    std::shared_ptr<Theater> theater = nullptr;
    for (auto& t : mTheaters)
    {
        if (t->getId() == theaterId)
        {
            theater = t;
            break;
        }
    }
    // Check if the theater was found
    if (!theater)
    {
        return false; // Theater not found
    }
    // If all seat IDs are valid and available, booked the seats one by one
    for (int seatId : seatIds) {
        if (!theater->bookSeat(seatId))
        {
            return false;
        }
    }
    return true; // Seats booked successfully
}
References isValidMovie(), isValidTheater(), mBookingMutex, and mTheaters.
getAllMovies()
const std::vector< std::shared_ptr< Movie > > & MovieBookingService::getAllMovies () const
Get a list of all playing movies.
Returns
A vector of Movie objects representing available movies.
{
    return mMovies;
}
References mMovies.
getAvailableSeats()
std::vector< int > MovieBookingService::getAvailableSeats (int theaterId, int movieId) const
Get available (free/unbooked) seats for a specific theater and movie.
Parameters
theaterId The ID of the theater.
movieId The ID of the movie.
Returns
A vector of seat IDs representing available seats.
{
    std::vector<int> availableSeats;
    // Check if the theater and movie IDs are valid
    if (!isValidTheater(theaterId) || !isValidMovie(movieId))
    {
        return availableSeats; // Return an empty vector for invalid theater or movie
    }
    if ( !isMovieShownInTheater(theaterId, movieId))
    {
        return availableSeats; // Return an empty vector for invalid theater or movie
    }
   // Find the theater associated with the provided theaterId
    std::shared_ptr<Theater> theater = nullptr;
    for (const auto& t : mTheaters)
    {
        if (t->getId() == theaterId)
        {
            theater = t;
            break;
        }
    }
    // Check if the theater was found
    if (!theater)
    {
        return availableSeats; // Return an empty vector if theater not found
    }
    availableSeats = theater->getAvailableSeats();
    return availableSeats;
}
References isMovieShownInTheater(), isValidMovie(), isValidTheater(), and mTheaters.
getMovieName()
std::string MovieBookingService::getMovieName (int movieId) const
Get the name of a movie by its ID.
Parameters
movieId The ID of the movie.
Returns
The name of the movie.
Note
Can throw invalid_argument exception
{
    for(auto& movie : mMovies)
    {
        if (movie->id == movieId)
        {
            return movie->name;
        }
    }
    // If the theater ID is not found, throw an exception
    throw std::invalid_argument("Movie with the specified ID not found");
}
References mMovies.
getTheaterName()
std::string MovieBookingService::getTheaterName (int theaterId) const
Get the name of a theater by its ID.
Parameters
theaterId The ID of the theater.
Returns
The name of the theater.
Note
Can throw invalid_argument exception
{
    for(auto& theater : mTheaters)
    {
        if (theater->getId() == theaterId)
        {
            return theater->getName();
        }
    }
    // If the theater ID is not found, throw an exception
    throw std::invalid_argument("Theater with the specified ID not found");
}
References mTheaters.
getTheatersForMovie()
std::vector< std::shared_ptr< Theater > > MovieBookingService::getTheatersForMovie (int movieId) const
Get theaters showing a specific movie.
Parameters
movieId The ID of the movie.
Returns
A vector of Theater objects showing the specified movie.
{
    std::vector<std::shared_ptr<Theater>> theatersForMovie;
    // Check if the movie ID is valid
    if (isValidMovie(movieId))
    {
        // Get the list of theater IDs allocated to the movie
        const std::vector<int>& theaterIds = mMovieTheaterAllocations.at(movieId);
        // Iterate through theaters and find matching theater IDs
        for (const auto& theater : mTheaters)
        {
            for (int allocatedTheaterId : theaterIds)
            {
                if (theater->getId() == allocatedTheaterId)
                {
                    theatersForMovie.push_back(theater);
                    break; // Found a matching theater, no need to continue searching
                }
            }
        }
    }
    return theatersForMovie;
}
References isValidMovie(), mMovieTheaterAllocations, and mTheaters.
isMovieShownInTheater()
bool MovieBookingService::isMovieShownInTheater (int theaterId, int movieId) const
Validate and check if a theater shows a given movie.
Parameters
theaterId The ID of the theater to check.
movieId The ID of the movie to check.
Returns
True if the movie is shown in the theater, false otherwise.
{
    // Check if the theater and movie IDs are valid
    if (!isValidTheater(theaterId) || !isValidMovie(movieId))
    {
        return false; // Invalid theater or movie
    }
    // Lock the mutex to protect the critical section
    std::lock_guard<std::mutex> lock(mBookingMutex);
    // Check if the specified theater is allocated for the given movie
    const std::vector<int>& allocatedTheaters = mMovieTheaterAllocations.at(movieId);
    bool isAllocated = std::find(allocatedTheaters.begin(), allocatedTheaters.end(), theaterId) != allocatedTheaters.end();
    return isAllocated;
}
References isValidMovie(), isValidTheater(), mBookingMutex, and mMovieTheaterAllocations.
Referenced by getAvailableSeats().
isValidMovie()
bool MovieBookingService::isValidMovie (int movieId) const
Check if a movie with a given ID exists.
Parameters
movieId The ID of the movie to check.
Returns
True if the movie exists, false otherwise.
{
    for (auto& movie : mMovies)
    {
        if (movie->id == movieId)
        {
            return true; // Found a movie with the specified ID
        }
    }
    return false; // Movie with the specified ID not found
}
References mMovies.
Referenced by allocateMovieToTheaters(), bookSeats(), getAvailableSeats(), getTheatersForMovie(), and isMovieShownInTheater().
isValidTheater()
bool MovieBookingService::isValidTheater (int theaterId) const private
Check if a theater with a given ID exists.
Parameters
theaterId The ID of the theater to check.
Returns
True if the theater exists, false otherwise.
{
    for (auto& theater : mTheaters)
    {
        if (theater->getId() == theaterId)
        {
            return true; // Found a theater with the specified ID
        }
    }
    return false; // Theater with the specified ID not found
}
References mTheaters.
Referenced by bookSeats(), getAvailableSeats(), and isMovieShownInTheater().
Member Data Documentation
mMovies
std::vector<std::shared_ptr<Movie> > MovieBookingService::mMovies private
Stores movie data
Referenced by addMovie(), addTheater(), getAllMovies(), getMovieName(), and isValidMovie().
mMovieTheaterAllocations
std::unordered_map<int, std::vector<int> > MovieBookingService::mMovieTheaterAllocations private
A map to track movie allocations to theaters.
This map associates movie IDs with vectors of theater IDs to represent which theaters are allocated for each movie.
Referenced by allocateMovieToTheaters(), getTheatersForMovie(), and isMovieShownInTheater().
mTheaters
std::vector<std::shared_ptr<Theater> > MovieBookingService::mTheaters private
Stores theater data
Referenced by addTheater(), allocateMovieToTheaters(), bookSeats(), getAvailableSeats(), getTheaterName(), getTheatersForMovie(), and isValidTheater().
The documentation for this class was generated from the following files:
include/movie_booking_service.hpp
src/movie_booking_service.cpp