Movie Ticket Booking Service: Theater Class Reference
Theater Class Reference
Represents a theater with an ID, name, and seats.
#include <theater.hpp>
Public Member Functions
Theater (const int &id, const std::string &name)
Constructor to initialize the theater with an ID and name.
bool bookSeat (const int &id)
Book a seat in the theater by its ID.
std::vector< int > getAvailableSeats () const
Get a vector of available seat IDs in the theater.
std::string getName () const
Get the name of the theater.
int getId () const
Get the ID of the theater.
bool operator== (const Theater &rhs) const
Equality operator for comparing Theaters based on their IDs.
Private Member Functions
void initializeSeats ()
Initialize the seats in the theater.
Private Attributes
int mId
std::string mName
const int mSeatCapacity
std::vector< Seat > mSeats
Detailed Description
Represents a theater with an ID, name, and seats.
The Theater class provides methods for managing seats in a theater.
Constructor & Destructor Documentation
Theater()
Theater::Theater (const int & id, const std::string & name)
Constructor to initialize the theater with an ID and name.
Parameters
id The unique identifier for the theater.
name The name of the theater.
                                                     :
mId(id), mName(name), mSeatCapacity(20)
{
    initializeSeats();
}
References initializeSeats().
Member Function Documentation
bookSeat()
bool Theater::bookSeat (const int & id)
Book a seat in the theater by its ID.
Parameters
id The ID of the seat to be booked.
Returns
True if the seat was booked successfully, false otherwise.
{
    for (auto& seat: mSeats)
    {
        if (seat.id == seatId)
        {
            if (seat.isBooked)
                return false; //Already booked
            else
            {
                seat.isBooked = true;
                return true;
            }
        }
    }
    return false;
}
References mSeats.
Referenced by MovieBookingService::bookSeats().
getAvailableSeats()
std::vector< int > Theater::getAvailableSeats () const
Get a vector of available seat IDs in the theater.
Returns
A vector of integers representing the available seat IDs.
{
    std::vector<int> availableSeats;
    for (const auto& seat: mSeats)
    {
        if(!seat.isBooked)
        {
            availableSeats.push_back(seat.id);
        }
    }
    return availableSeats;
}
References mSeats.
Referenced by MovieBookingService::getAvailableSeats().
getId()
int Theater::getId () const inline
Get the ID of the theater.
Returns
The ID of the theater as an integer.
{ return mId; }
References mId.
getName()
std::string Theater::getName () const inline
Get the name of the theater.
Returns
The name of the theater as a string.
{ return mName;}
References mName.
Referenced by MovieBookingService::getMovieName().
initializeSeats()
void Theater::initializeSeats () private
Initialize the seats in the theater.
This function initializes the seats in the theater based on the specified seat capacity.
{
    for (int i = 0; i < mSeatCapacity; ++i) {
        Seat seat;
        seat.id = i;
        seat.seatNumber = "Seat " + std::to_string(i + 1);
        seat.isBooked = false;
        mSeats.push_back(seat);
    }
}
References Seat::id, Seat::isBooked, mSeatCapacity, mSeats, and Seat::seatNumber.
Referenced by Theater().
operator==()
bool Theater::operator== (const Theater & rhs) const
Equality operator for comparing Theaters based on their IDs.
Parameters
rhs The theater to compare with.
Returns
True if the theater have the same ID, false otherwise.
{
    if (mId == rhs.mId)
        return true;
    return false;
}
References mId.
Member Data Documentation
mId
int Theater::mId private
Unique identifier for the theater.
Referenced by getId(), and operator==().
mName
std::string Theater::mName private
Name of the theater.
Referenced by getName().
mSeatCapacity
const int Theater::mSeatCapacity private
Capacity of the theater in terms of seats.
Referenced by initializeSeats().
mSeats
std::vector<Seat> Theater::mSeats private
Vector of seats in the theater.
Referenced by bookSeat(), getAvailableSeats(), and initializeSeats().
The documentation for this class was generated from the following files:
include/theater.hpp
src/theater.cpp