name: Build Movie Booking system

on:
  push:
    branches:
      - main  # Change to your repository's main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can specify the runner OS here

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/run-cmake@v1

    - name: Build Project
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    # Add more steps here for testing or deploying your project if needed
