name: Build Movie Booking system

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # You can specify the runner OS here

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: lukka/run-cmake@v1

    - name: Install Dependencies
      run: sudo apt-get install -y googletest

    - name: Configure Project with CMake
      run: cmake -Bbuild -H. -DCMAKE_MAKE_PROGRAM=make

    - name: Build Project
      run: cmake --build build

    #- name: Build Project
      #run: |
        #mkdir -p build
        #cd build
        #cmake ..
        #make
